// Data mock katalog kelas Codeverse. Dipakai bersama oleh halaman yang menampilkan
// kartu kelas (index.html, pages/courses.html, pages/dashboard.html) dan halaman
// detail (pages/course-detail.html) supaya kontennya konsisten satu sumber data.

const COURSES_DATA = {
  'literasi-digital-pemula': {
    category: 'Literasi Digital Dasar',
    title: 'Literasi Digital untuk Pemula',
    icon: '💻',
    duration: '4 jam',
    participants: '3.200 peserta',
    videos: '18 video',
    rating: '4.9',
    description: 'Kelas dasar untuk memahami perangkat, internet, email, dan keamanan digital sehari-hari — dirancang untuk yang benar-benar baru mengenal teknologi.',
    fullDescription: 'Kelas ini cocok untuk pelajar, pencari kerja, maupun anggota keluarga yang ingin mulai percaya diri menggunakan perangkat digital: mulai dari mengoperasikan komputer/HP, membuat email profesional, hingga mengenali penipuan digital yang umum terjadi.',
    curriculum: [
      { title: 'Mengenal Perangkat & Internet', duration: '20 menit', done: true },
      { title: 'Membuat & Mengelola Email', duration: '35 menit', done: true },
      { title: 'Mengenali Penipuan Digital', duration: '40 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'RA', name: 'Rina A.', text: 'Penjelasannya pelan-pelan dan mudah diikuti walau saya jarang pakai komputer.' },
      { initials: 'DP', name: 'Dewi P.', text: 'Materi keamanan digitalnya sangat relevan buat sehari-hari.' },
    ],
  },
  'office-produktivitas-kerja': {
    category: 'Produktivitas & Perkantoran',
    title: 'Microsoft Office untuk Produktivitas Kerja',
    icon: '📊',
    duration: '6 jam',
    participants: '2.750 peserta',
    videos: '24 video',
    rating: '4.8',
    description: 'Kuasai Word, Excel, dan PowerPoint untuk kebutuhan kerja sehari-hari, dari surat lamaran sampai laporan bulanan.',
    fullDescription: 'Kelas ini membekali kamu dengan keterampilan Office yang paling sering diminta di dunia kerja: menulis dokumen rapi di Word, mengolah data dengan rumus dasar Excel, dan membuat presentasi yang meyakinkan di PowerPoint.',
    curriculum: [
      { title: 'Dasar Microsoft Word', duration: '45 menit', done: true },
      { title: 'Rumus & Tabel Excel Dasar', duration: '1 jam', done: false },
      { title: 'Membuat Presentasi PowerPoint', duration: '50 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'BS', name: 'Budi S.', text: 'Rumus Excel yang diajarkan langsung kepakai buat laporan toko saya.' },
      { initials: 'NA', name: 'Nadia A.', text: 'Format CV & surat lamaran saya jadi jauh lebih rapi.' },
    ],
  },
  'pemasaran-digital-umkm': {
    category: 'Pemasaran Digital',
    title: 'Dasar Pemasaran Digital untuk UMKM',
    icon: '📱',
    duration: '5 jam',
    participants: '4.100 peserta',
    videos: '20 video',
    rating: '4.9',
    description: 'Belajar strategi promosi produk lewat media sosial dan marketplace, dirancang khusus untuk pelaku usaha kecil.',
    fullDescription: 'Kelas ini membahas cara memasarkan produk UMKM secara digital: menyusun konten promosi yang menarik, memilih platform yang tepat, hingga membaca data sederhana untuk mengetahui promosi mana yang paling efektif.',
    curriculum: [
      { title: 'Mengenal Kanal Pemasaran Digital', duration: '30 menit', done: true },
      { title: 'Menyusun Konten Promosi', duration: '45 menit', done: true },
      { title: 'Iklan Berbayar untuk Pemula', duration: '50 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'BS', name: 'Budi S.', text: 'Jalur Pemasaran Digital UMKM langsung bisa dipraktikkan ke toko online saya. Penjualan naik dalam sebulan.' },
      { initials: 'SW', name: 'Siti W.', text: 'Tips kontennya sederhana tapi ngena, cocok untuk pemula seperti saya.' },
    ],
  },
  'coding-dasar-website': {
    category: 'Coding Dasar',
    title: 'Membuat Website Pertamamu',
    icon: '🌐',
    duration: '8 jam',
    participants: '1.980 peserta',
    videos: '32 video',
    rating: '4.7',
    description: 'Belajar HTML, CSS, dan sedikit JavaScript untuk membangun website sederhana dari nol, tanpa pengalaman coding sebelumnya.',
    fullDescription: 'Kelas ini menuntunmu membuat website pertama langkah demi langkah: struktur halaman dengan HTML, mempercantik tampilan dengan CSS, dan menambahkan interaksi dasar dengan JavaScript.',
    curriculum: [
      { title: 'Struktur Dasar HTML', duration: '1 jam', done: true },
      { title: 'Mempercantik dengan CSS', duration: '1,5 jam', done: false },
      { title: 'Interaksi Dasar dengan JavaScript', duration: '2 jam', done: false },
      { title: 'Proyek Akhir & Sertifikasi', duration: '30 menit', done: false },
    ],
    reviews: [
      { initials: 'DP', name: 'Dewi P.', text: 'Forum diskusinya aktif, jadi walau belajar online saya tetap dibantu teman satu jalur belajar.' },
      { initials: 'AF', name: 'Andi F.', text: 'Baru pertama kali coding tapi bisa ikut sampai selesai, penjelasannya runtut.' },
    ],
  },
  'keamanan-data-privasi': {
    category: 'Literasi Digital Dasar',
    title: 'Keamanan Data & Privasi di Internet',
    icon: '🔒',
    duration: '3 jam',
    participants: '2.400 peserta',
    videos: '14 video',
    rating: '4.8',
    description: 'Pahami cara melindungi data pribadi, mengenali phishing, dan menjaga akun digital tetap aman.',
    fullDescription: 'Kelas ini membahas ancaman digital yang paling umum dihadapi masyarakat: kata sandi lemah, tautan phishing, dan penipuan berkedok hadiah — lengkap dengan langkah konkret untuk melindungi diri.',
    curriculum: [
      { title: 'Mengenali Phishing & Penipuan Online', duration: '40 menit', done: true },
      { title: 'Kata Sandi Kuat & Verifikasi Dua Langkah', duration: '35 menit', done: true },
      { title: 'Menjaga Privasi di Media Sosial', duration: '30 menit', done: true },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: true },
    ],
    reviews: [
      { initials: 'RA', name: 'Rina A.', text: 'Sekarang saya jauh lebih waspada sama link mencurigakan di WhatsApp.' },
      { initials: 'NA', name: 'Nadia A.', text: 'Materinya singkat tapi langsung ke praktik, mudah diikuti.' },
    ],
  },
  'desain-konten-canva': {
    category: 'Pemasaran Digital',
    title: 'Desain Konten dengan Canva',
    icon: '🎨',
    duration: '4 jam',
    participants: '3.600 peserta',
    videos: '16 video',
    rating: '4.9',
    description: 'Belajar membuat desain promosi, poster, dan konten media sosial yang menarik pakai Canva, tanpa perlu skill desain sebelumnya.',
    fullDescription: 'Kelas ini mengajarkan dasar-dasar desain grafis praktis menggunakan Canva: memilih template, mengatur warna dan tipografi, hingga menyusun konten media sosial yang konsisten untuk usaha atau personal branding.',
    curriculum: [
      { title: 'Mengenal Canva & Template', duration: '30 menit', done: false },
      { title: 'Warna, Font, dan Layout', duration: '45 menit', done: false },
      { title: 'Membuat Konten Media Sosial', duration: '1 jam', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'SW', name: 'Siti W.', text: 'Desain feed Instagram toko saya jadi jauh lebih rapi dan konsisten.' },
      { initials: 'AF', name: 'Andi F.', text: 'Templatenya gampang diikuti bahkan buat yang nggak bisa desain sama sekali.' },
    ],
  },
};
