// Data mock katalog kelas EduVerse. Dipakai bersama oleh halaman yang menampilkan
// kartu kelas (index.html, pages/courses.html, pages/dashboard.html) dan halaman
// detail (pages/course-detail.html) supaya kontennya konsisten satu sumber data.

const COURSES_DATA = {
  'literasi-digital-pemula': {
    category: 'Literasi Digital Dasar',
    title: 'Literasi Digital untuk Pemula',
    image: 'https://images.unsplash.com/photo-1758270705290-62b6294dd044?auto=format&fit=crop&w=1200&q=80',
    duration: '4 jam',
    participants: '3.200 peserta',
    videos: '18 video',
    rating: '4.9',
    description: 'Kelas dasar untuk memahami perangkat, internet, email, dan keamanan digital sehari-hari — dirancang untuk yang benar-benar baru mengenal teknologi.',
    fullDescription: 'Kelas ini cocok untuk pelajar, pencari kerja, maupun anggota keluarga yang ingin mulai percaya diri menggunakan perangkat digital: mulai dari mengoperasikan komputer/HP, membuat email profesional, hingga mengenali penipuan digital yang umum terjadi.',
    curriculum: [
      { title: 'Mengenal Perangkat & Internet', duration: '20 menit', done: true },
      { title: 'Membuat & Mengelola Email', duration: '35 menit', done: true },
      { title: 'Mengenali Penipuan Digital', duration: '40 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'RA', name: 'Rina A.', text: 'Penjelasannya pelan-pelan dan mudah diikuti walau saya jarang pakai komputer.' },
      { initials: 'DP', name: 'Dewi P.', text: 'Materi keamanan digitalnya sangat relevan buat sehari-hari.' },
    ],
  },
  'office-produktivitas-kerja': {
    category: 'Produktivitas & Perkantoran',
    title: 'Microsoft Office untuk Produktivitas Kerja',
    image: 'https://images.unsplash.com/photo-1507206130118-b5907f817163?auto=format&fit=crop&w=1200&q=80',
    duration: '6 jam',
    participants: '2.750 peserta',
    videos: '24 video',
    rating: '4.8',
    description: 'Kuasai Word, Excel, dan PowerPoint untuk kebutuhan kerja sehari-hari, dari surat lamaran sampai laporan bulanan.',
    fullDescription: 'Kelas ini membekali kamu dengan keterampilan Office yang paling sering diminta di dunia kerja: menulis dokumen rapi di Word, mengolah data dengan rumus dasar Excel, dan membuat presentasi yang meyakinkan di PowerPoint.',
    curriculum: [
      { title: 'Dasar Microsoft Word', duration: '45 menit', done: true },
      { title: 'Rumus & Tabel Excel Dasar', duration: '1 jam', done: false },
      { title: 'Membuat Presentasi PowerPoint', duration: '50 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'BS', name: 'Budi S.', text: 'Rumus Excel yang diajarkan langsung kepakai buat laporan toko saya.' },
      { initials: 'NA', name: 'Nadia A.', text: 'Format CV & surat lamaran saya jadi jauh lebih rapi.' },
    ],
  },
  'pemasaran-digital-umkm': {
    category: 'Pemasaran Digital',
    title: 'Dasar Pemasaran Digital untuk UMKM',
    image: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=1200&q=80',
    duration: '5 jam',
    participants: '4.100 peserta',
    videos: '20 video',
    rating: '4.9',
    description: 'Belajar strategi promosi produk lewat media sosial dan marketplace, dirancang khusus untuk pelaku usaha kecil.',
    fullDescription: 'Kelas ini membahas cara memasarkan produk UMKM secara digital: menyusun konten promosi yang menarik, memilih platform yang tepat, hingga membaca data sederhana untuk mengetahui promosi mana yang paling efektif.',
    curriculum: [
      { title: 'Mengenal Kanal Pemasaran Digital', duration: '30 menit', done: true },
      { title: 'Menyusun Konten Promosi', duration: '45 menit', done: true },
      { title: 'Iklan Berbayar untuk Pemula', duration: '50 menit', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'BS', name: 'Budi S.', text: 'Jalur Pemasaran Digital UMKM langsung bisa dipraktikkan ke toko online saya. Penjualan naik dalam sebulan.' },
      { initials: 'SW', name: 'Siti W.', text: 'Tips kontennya sederhana tapi ngena, cocok untuk pemula seperti saya.' },
    ],
  },
  'coding-dasar-website': {
    category: 'Coding Dasar',
    title: 'Membuat Website Pertamamu',
    image: 'https://images.unsplash.com/photo-1569748130764-3fed0c102c59?auto=format&fit=crop&w=1200&q=80',
    duration: '8 jam',
    participants: '1.980 peserta',
    videos: '32 video',
    rating: '4.7',
    description: 'Belajar HTML, CSS, dan sedikit JavaScript untuk membangun website sederhana dari nol, tanpa pengalaman coding sebelumnya.',
    fullDescription: 'Kelas ini menuntunmu membuat website pertama langkah demi langkah: struktur halaman dengan HTML, mempercantik tampilan dengan CSS, dan menambahkan interaksi dasar dengan JavaScript.',
    curriculum: [
      { title: 'Struktur Dasar HTML', duration: '1 jam', done: true },
      { title: 'Mempercantik dengan CSS', duration: '1,5 jam', done: false },
      { title: 'Interaksi Dasar dengan JavaScript', duration: '2 jam', done: false },
      { title: 'Proyek Akhir & Sertifikasi', duration: '30 menit', done: false },
    ],
    reviews: [
      { initials: 'DP', name: 'Dewi P.', text: 'Forum diskusinya aktif, jadi walau belajar online saya tetap dibantu teman satu jalur belajar.' },
      { initials: 'AF', name: 'Andi F.', text: 'Baru pertama kali coding tapi bisa ikut sampai selesai, penjelasannya runtut.' },
    ],
  },
  'keamanan-data-privasi': {
    category: 'Literasi Digital Dasar',
    title: 'Keamanan Data & Privasi di Internet',
    image: 'https://images.unsplash.com/photo-1768839720936-87ce3adf2d08?auto=format&fit=crop&w=1200&q=80',
    duration: '3 jam',
    participants: '2.400 peserta',
    videos: '14 video',
    rating: '4.8',
    description: 'Pahami cara melindungi data pribadi, mengenali phishing, dan menjaga akun digital tetap aman.',
    fullDescription: 'Kelas ini membahas ancaman digital yang paling umum dihadapi masyarakat: kata sandi lemah, tautan phishing, dan penipuan berkedok hadiah — lengkap dengan langkah konkret untuk melindungi diri.',
    curriculum: [
      { title: 'Mengenali Phishing & Penipuan Online', duration: '40 menit', done: true },
      { title: 'Kata Sandi Kuat & Verifikasi Dua Langkah', duration: '35 menit', done: true },
      { title: 'Menjaga Privasi di Media Sosial', duration: '30 menit', done: true },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: true },
    ],
    reviews: [
      { initials: 'RA', name: 'Rina A.', text: 'Sekarang saya jauh lebih waspada sama link mencurigakan di WhatsApp.' },
      { initials: 'NA', name: 'Nadia A.', text: 'Materinya singkat tapi langsung ke praktik, mudah diikuti.' },
    ],
  },
  'desain-konten-canva': {
    category: 'Pemasaran Digital',
    title: 'Desain Konten dengan Canva',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    duration: '4 jam',
    participants: '3.600 peserta',
    videos: '16 video',
    rating: '4.9',
    description: 'Belajar membuat desain promosi, poster, dan konten media sosial yang menarik pakai Canva, tanpa perlu skill desain sebelumnya.',
    fullDescription: 'Kelas ini mengajarkan dasar-dasar desain grafis praktis menggunakan Canva: memilih template, mengatur warna dan tipografi, hingga menyusun konten media sosial yang konsisten untuk usaha atau personal branding.',
    curriculum: [
      { title: 'Mengenal Canva & Template', duration: '30 menit', done: false },
      { title: 'Warna, Font, dan Layout', duration: '45 menit', done: false },
      { title: 'Membuat Konten Media Sosial', duration: '1 jam', done: false },
      { title: 'Kuis & Sertifikasi', duration: '15 menit', done: false },
    ],
    reviews: [
      { initials: 'SW', name: 'Siti W.', text: 'Desain feed Instagram toko saya jadi jauh lebih rapi dan konsisten.' },
      { initials: 'AF', name: 'Andi F.', text: 'Templatenya gampang diikuti bahkan buat yang nggak bisa desain sama sekali.' },
    ],
  },
  'generative-ai-specialist': {
    category: 'Artificial Intelligence',
    title: 'Generative AI Specialist',
    image: '../img/certificate_1.jpg',
    duration: '12 jam',
    participants: '4.800 peserta',
    videos: '36 video',
    rating: '4.9',
    description: 'Pelajari dasar hingga penerapan Generative AI untuk membuat solusi kerja yang lebih cepat dan kreatif.',
    fullDescription: 'Kelas ini membahas cara kerja model generatif, teknik menulis prompt, evaluasi output, dan penerapan AI yang bertanggung jawab untuk kebutuhan profesional.',
    curriculum: [
      { title: 'Dasar Generative AI', duration: '1 jam', done: true },
      { title: 'Prompt Engineering', duration: '2 jam', done: false },
      { title: 'Membangun Workflow AI', duration: '3 jam', done: false },
      { title: 'Proyek Akhir & Sertifikasi', duration: '1 jam', done: false },
    ],
    reviews: [
      { initials: 'NA', name: 'Nadia A.', text: 'Contoh prompt dan workflow-nya langsung membantu pekerjaan sehari-hari.' },
      { initials: 'AF', name: 'Andi F.', text: 'Materinya runtut dari konsep sampai praktik, cocok untuk pemula.' },
    ],
  },
  'ai-machine-learning-engineer': {
    category: 'Artificial Intelligence',
    title: 'AI & Machine Learning Engineer',
    image: '../img/certificate_2.jpeg',
    duration: '18 jam',
    participants: '3.900 peserta',
    videos: '48 video',
    rating: '4.9',
    description: 'Bangun fondasi machine learning, mulai dari pengolahan data hingga evaluasi model prediktif.',
    fullDescription: 'Kelas ini mengajarkan alur kerja machine learning secara praktis: menyiapkan data, memilih algoritma, melatih model, mengukur performa, dan menyusun eksperimen yang dapat diulang.',
    curriculum: [
      { title: 'Pengantar Machine Learning', duration: '2 jam', done: true },
      { title: 'Data Preparation', duration: '3 jam', done: false },
      { title: 'Training & Evaluasi Model', duration: '4 jam', done: false },
      { title: 'Proyek Prediksi', duration: '3 jam', done: false },
    ],
    reviews: [
      { initials: 'DP', name: 'Dewi P.', text: 'Penjelasan evaluasi modelnya jelas dan tidak berhenti di teori.' },
      { initials: 'BS', name: 'Budi S.', text: 'Latihannya membuat saya lebih percaya diri membaca hasil model.' },
    ],
  },
  'ai-product-manager': {
    category: 'Product & Technology',
    title: 'AI Product Manager',
    image: '../img/certificate_3.jpg',
    duration: '10 jam',
    participants: '2.700 peserta',
    videos: '28 video',
    rating: '4.9',
    description: 'Pelajari cara merancang produk berbasis AI yang bermanfaat, terukur, dan sesuai kebutuhan pengguna.',
    fullDescription: 'Kelas ini membahas discovery, validasi masalah, pemilihan use case AI, penyusunan roadmap, serta metrik untuk mengukur keberhasilan produk secara bertanggung jawab.',
    curriculum: [
      { title: 'Memahami Produk AI', duration: '1 jam', done: true },
      { title: 'Menemukan Use Case Bernilai', duration: '2 jam', done: false },
      { title: 'Roadmap & Eksperimen Produk', duration: '3 jam', done: false },
      { title: 'Proyek Product Brief', duration: '2 jam', done: false },
    ],
    reviews: [
      { initials: 'RA', name: 'Rina A.', text: 'Kerangka product brief-nya sangat membantu menyusun ide dengan lebih terarah.' },
      { initials: 'SW', name: 'Siti W.', text: 'Materinya membuat sisi bisnis dan teknis terasa lebih mudah dipahami.' },
    ],
  },
  'computer-vision-nlp-specialist': {
    category: 'Artificial Intelligence',
    title: 'Computer Vision & NLP Specialist',
    image: '../img/certificate_4.jpg',
    duration: '20 jam',
    participants: '2.300 peserta',
    videos: '52 video',
    rating: '4.9',
    description: 'Kenali penerapan computer vision dan natural language processing untuk memecahkan masalah dunia nyata.',
    fullDescription: 'Kelas ini memperkenalkan teknik penting untuk memahami gambar dan bahasa: preprocessing, klasifikasi, ekstraksi fitur, text classification, dan evaluasi hasil model.',
    curriculum: [
      { title: 'Dasar Computer Vision', duration: '3 jam', done: true },
      { title: 'Klasifikasi dan Ekstraksi Fitur', duration: '4 jam', done: false },
      { title: 'Dasar Natural Language Processing', duration: '4 jam', done: false },
      { title: 'Proyek Vision atau NLP', duration: '4 jam', done: false },
    ],
    reviews: [
      { initials: 'NA', name: 'Nadia A.', text: 'Studi kasusnya membantu saya memahami kapan memakai vision atau NLP.' },
      { initials: 'DP', name: 'Dewi P.', text: 'Materi teknisnya padat tetapi tetap dijelaskan dengan contoh yang konkret.' },
    ],
  },
};
